accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$',views.signup_view,name='signup'),
    url(r'^login/$',views.login_view,name='login'),
    url(r'^logout/$',views.logout_view,name='logout'),
    url(r'^contectus/$',views.contect_us,name='contectus'),
]

articles/urls.py
from django.conf.urls import url
from . import views

app_name = 'articles'

urlpatterns = [
    url(r'^$', views.article_list, name="list"),
    url(r'^create/$', views.article_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name="detail"),
]

dawn/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from dawn import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^articles/',include('articles.urls')),
    url(r'^about/$',views.about ),
    url(r'^$',article_views.article_list,name="home" ),
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title=models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    link = models.TextField(default=None, blank=True, null=True)
    thumb = models.ImageField(default='default.jpg',blank=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE,default=None)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:25] +'...'

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title','body','slug','thumb']

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html',{'form':form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

def contect_us(request):
    return render(request, 'accounts/contectus.html')

articles/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Article
from django.contrib.auth.decorators import login_required
from . import forms
# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by('date');
    return render(request, 'articles/article_list.html', { 'articles': articles })

def article_detail(request, slug):
    # return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    article.body1 = article.body.split("*")
    article.body2 = article.body1[1]
    article.body3 = article.body1[2]
    article.body4 = article.body1[3]
    article.body5 = article.body1[4]
    article.body6 = article.body1[5]
    return render(request, 'articles/article_detail.html', {'article': article})

@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request,'articles/article_create.html',{'form':form })

dawn/views.py
from django.http import HttpResponse
from django.shortcuts import render

def HomePage(request):
    #return HttpResponse('home')
     return render(request,'HomePage.html')

def about(request):
    #return HttpResponse('about')
    return render(request, 'About.html')

accounts/templates/accounts/contectus.html
{% extends 'base_layout.html' %}


{% block content %}

   <h2> To Sign Up and Add Article </h2>
   <p id="rcorners1">
       Contect Information
       <br>
       <br><br>
       Email   &nbsp: vyshakhams444@gmail.com
       <br><br>
       Twitter: @vyshakhams1
   </p>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}


{% block content %}
    <h1>Log in</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}" />
        {% endif %}
        <input disabled type="submit" value="Login" />
    </form>
    <p>Not got an account? <a href="{% url 'accounts:signup' %}">Sign Up</a></p>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}
{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input disabled type="submit" value="Signup">
    </form>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}
{% block content %}
    <div class="create-article">
        <h2>Create an Awesome New Article</h2>
        <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
    <script src="/static/slugify.js"></script>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}
{% block content %}

{% if  article.link  %}
<div class="link">

<h2>hello</h2>
<a href="{{ article.link }}"> click here </a>
{% endif %}

</div>

<div class="article-detail">
    <div class="article">
        <center>
               <img src="{{ article.thumb.url }}" width="400px" height="400px"  />
         </center>
        <h2>{{ article.title }}</h2>


      <ol>
       <li> <p> {{ article.body2 }}</p></li>
       <li><p> {{ article.body3 }}</p></li>
       <li> <p>{{ article.body4 }}</p></li>
       <li> <p>{{ article.body5 }}</p></li>
       <li><p>{{ article.body6 }}</p> </li>
          
       </ol>

        <p>{{ article.date }}</p>
        <h3>Written by {{ article.author.username }}</h3>
    </div>
</div>

{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content%}
    <h1>Articles List</h1>
    <div class="articles">
    {% for article in articles %}
        <div class="article">
            <h2><a id="articletitle" href="{% url 'articles:detail' slug=article.slug %}"> <h2>{{ article.title }}</h2></a></h2>
            <p> {{ article.snippet }}</p>
            <p>{{ article.date }}</p>
            <p class="author">added by {{ article.author.username }}</p>
        </div>
    {% endfor %}
    </div>

 {% endblock %}

templates/About.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="wrapper">
    <h1>About Us</h1>
    <p>We like django.</p>
</div>
{% endblock %}

templates/HomePage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HomePage</title>
</head>
<body>
<h1> WelCome to HomePage</h1>

</body>
</html>

templates/base_layout.html
{%load static from staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Articles</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
    </head>
    <body>
    <body>
    <div hidden>
        <----------------------------------------------------------------------------------->
                          Hi thanks for comming here!!!
                      If you are interested in logging error
                       email me @ vyshakhams444@gmail.com
                     for every error you will get Assured GIFT :)
        <----------------------------------------------------------------------------------->

    </div>
        <header class="wrapper">
            <h1><a href="{% url 'home' %}"><img src="{% static 'logo1.jpg' %}" alt="djangonautic" width="200px" height="125px" /></a></h1>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                    <li><a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
                    {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                     <li><a href="{% url 'accounts:contectus' %}">About Us</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>

</body>
</html>